const coffeeTemplate = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><script src="https://cdn.tailwindcss.com"></script><title>BREW Coffee</title></head><body class="bg-gray-950 text-white font-sans">
<nav class="fixed w-full z-50 bg-gray-950/80 backdrop-blur-xl border-b border-white/5"><div class="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center"><a href="#" class="text-2xl font-black tracking-tighter">BREW<span class="text-amber-500">.</span></a><div class="hidden md:flex gap-8 text-sm text-gray-400"><a href="#menu" class="hover:text-white transition">Menu</a><a href="#story" class="hover:text-white transition">Our Story</a><a href="#locations" class="hover:text-white transition">Locations</a><a href="#contact" class="hover:text-white transition">Contact</a></div><a href="#" class="bg-amber-500 hover:bg-amber-600 text-black px-6 py-2.5 rounded-full text-sm font-bold transition">Order Now</a></div></nav>
<section class="min-h-screen flex items-center pt-20 relative overflow-hidden"><div class="absolute inset-0 bg-gradient-to-br from-amber-900/20 via-transparent to-transparent"></div><div class="max-w-7xl mx-auto px-6 grid md:grid-cols-2 gap-16 items-center relative z-10"><div><p class="text-amber-500 font-bold text-sm uppercase tracking-widest mb-4">Est. 2019 — Specialty Coffee</p><h1 class="text-6xl md:text-8xl font-black leading-none tracking-tighter mb-6">Coffee<br/>Crafted<br/>With <span class="text-amber-500">Soul</span></h1><p class="text-gray-400 text-lg max-w-md mb-8">Every cup tells a story. We source single-origin beans from Ethiopia, Colombia, and Guatemala — roasted fresh daily in small batches.</p><div class="flex gap-4"><a href="#" class="bg-amber-500 hover:bg-amber-600 text-black px-8 py-4 rounded-full font-bold transition">Explore Menu</a><a href="#" class="border border-white/20 hover:border-white/40 px-8 py-4 rounded-full font-bold transition">Our Story</a></div></div><div class="relative"><div class="w-80 h-80 md:w-[500px] md:h-[500px] bg-gradient-to-br from-amber-800 to-amber-950 rounded-full mx-auto flex items-center justify-center"><span class="text-9xl">☕</span></div></div></div></section>
<section id="menu" class="py-32"><div class="max-w-7xl mx-auto px-6"><p class="text-amber-500 font-bold text-sm uppercase tracking-widest mb-2">Our Selection</p><h2 class="text-5xl font-black tracking-tighter mb-16">The Menu</h2><div class="grid md:grid-cols-3 gap-8">
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-amber-500/30 transition group"><div class="text-5xl mb-6">🫘</div><h3 class="text-xl font-bold mb-2">Single Origin Pour Over</h3><p class="text-gray-500 text-sm mb-4">Hand-poured Ethiopian Yirgacheffe with notes of blueberry and dark chocolate.</p><span class="text-amber-500 font-bold text-lg">$5.50</span></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-amber-500/30 transition group"><div class="text-5xl mb-6">🥛</div><h3 class="text-xl font-bold mb-2">Oat Milk Latte</h3><p class="text-gray-500 text-sm mb-4">Silky smooth espresso blended with house-made oat milk and a hint of vanilla.</p><span class="text-amber-500 font-bold text-lg">$6.00</span></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-amber-500/30 transition group"><div class="text-5xl mb-6">🍵</div><h3 class="text-xl font-bold mb-2">Matcha Ceremony</h3><p class="text-gray-500 text-sm mb-4">Ceremonial-grade matcha from Kyoto, whisked to perfection and served hot or iced.</p><span class="text-amber-500 font-bold text-lg">$6.50</span></div>
</div></div></section>
<section class="py-32 bg-gradient-to-b from-gray-950 to-gray-900"><div class="max-w-7xl mx-auto px-6 text-center"><h2 class="text-5xl font-black tracking-tighter mb-16">What People Say</h2><div class="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
<div class="bg-gray-800/30 border border-white/5 rounded-3xl p-8 text-left"><p class="text-gray-300 mb-6">"The best pour-over I've ever had. You can taste the difference quality beans make. BREW has ruined every other coffee shop for me."</p><div class="flex items-center gap-3"><div class="w-10 h-10 bg-amber-500 rounded-full flex items-center justify-center font-bold text-black">S</div><div><p class="font-bold text-sm">Sarah Chen</p><p class="text-gray-500 text-xs">Regular since 2020</p></div></div></div>
<div class="bg-gray-800/30 border border-white/5 rounded-3xl p-8 text-left"><p class="text-gray-300 mb-6">"I come here every morning before work. The atmosphere, the music, the coffee — everything is intentional. This is what coffee culture should be."</p><div class="flex items-center gap-3"><div class="w-10 h-10 bg-amber-500 rounded-full flex items-center justify-center font-bold text-black">M</div><div><p class="font-bold text-sm">Marcus Rivera</p><p class="text-gray-500 text-xs">Coffee Enthusiast</p></div></div></div>
</div></div></section>
<footer class="border-t border-white/5 py-16"><div class="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8"><p class="text-2xl font-black tracking-tighter">BREW<span class="text-amber-500">.</span></p><div class="flex gap-8 text-sm text-gray-500"><a href="#" class="hover:text-white transition">Instagram</a><a href="#" class="hover:text-white transition">Twitter</a><a href="#" class="hover:text-white transition">Careers</a></div><p class="text-gray-600 text-sm">© 2026 BREW Coffee Co. All rights reserved.</p></div></footer>
</body></html>`;

const fitnessTemplate = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><script src="https://cdn.tailwindcss.com"></script><title>FORGE Fitness</title></head><body class="bg-black text-white font-sans">
<nav class="fixed w-full z-50 bg-black/80 backdrop-blur-xl border-b border-white/5"><div class="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center"><a href="#" class="text-2xl font-black tracking-tighter">FORGE<span class="text-red-500">.</span></a><div class="hidden md:flex gap-8 text-sm text-gray-400"><a href="#programs" class="hover:text-white transition">Programs</a><a href="#trainers" class="hover:text-white transition">Trainers</a><a href="#pricing" class="hover:text-white transition">Pricing</a></div><a href="#" class="bg-red-600 hover:bg-red-700 px-6 py-2.5 rounded-full text-sm font-bold transition">Start Free Trial</a></div></nav>
<section class="min-h-screen flex items-center pt-20"><div class="max-w-7xl mx-auto px-6"><p class="text-red-500 font-bold text-sm uppercase tracking-widest mb-4">No Excuses. Just Results.</p><h1 class="text-7xl md:text-9xl font-black leading-none tracking-tighter mb-6">BREAK<br/>YOUR<br/><span class="text-red-500">LIMITS</span></h1><p class="text-gray-400 text-lg max-w-lg mb-8">Elite training programs designed by world-class coaches. Transform your body and mind in 90 days or your money back.</p><div class="flex gap-4"><a href="#" class="bg-red-600 hover:bg-red-700 px-8 py-4 rounded-full font-bold transition">Join Now — $49/mo</a><a href="#" class="border border-white/20 hover:border-white/40 px-8 py-4 rounded-full font-bold transition">Watch Video</a></div><div class="flex gap-12 mt-16 text-center"><div><p class="text-4xl font-black text-red-500">50K+</p><p class="text-gray-500 text-sm">Members</p></div><div><p class="text-4xl font-black text-red-500">200+</p><p class="text-gray-500 text-sm">Classes/Week</p></div><div><p class="text-4xl font-black text-red-500">98%</p><p class="text-gray-500 text-sm">Satisfaction</p></div></div></div></section>
<section id="programs" class="py-32"><div class="max-w-7xl mx-auto px-6"><h2 class="text-5xl font-black tracking-tighter mb-16">Programs</h2><div class="grid md:grid-cols-3 gap-8">
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-red-500/30 transition"><div class="text-4xl mb-4">🏋️</div><h3 class="text-xl font-bold mb-2">Strength & Power</h3><p class="text-gray-500 text-sm">Olympic lifting, powerlifting, and functional strength training with certified coaches.</p></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-red-500/30 transition"><div class="text-4xl mb-4">🥊</div><h3 class="text-xl font-bold mb-2">Combat Training</h3><p class="text-gray-500 text-sm">Boxing, kickboxing, and MMA fundamentals. Build confidence and get fight-ready.</p></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-red-500/30 transition"><div class="text-4xl mb-4">🧘</div><h3 class="text-xl font-bold mb-2">Recovery & Mobility</h3><p class="text-gray-500 text-sm">Yoga, stretching, and recovery sessions to keep your body performing at its peak.</p></div>
</div></div></section>
<footer class="border-t border-white/5 py-16"><div class="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8"><p class="text-2xl font-black tracking-tighter">FORGE<span class="text-red-500">.</span></p><p class="text-gray-600 text-sm">© 2026 FORGE Fitness. All rights reserved.</p></div></footer>
</body></html>`;

const agencyTemplate = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><script src="https://cdn.tailwindcss.com"></script><title>NOVA Creative Agency</title></head><body class="bg-gray-950 text-white font-sans">
<nav class="fixed w-full z-50 bg-gray-950/80 backdrop-blur-xl border-b border-white/5"><div class="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center"><a href="#" class="text-2xl font-black tracking-tighter">NOVA<span class="text-violet-500">.</span></a><div class="hidden md:flex gap-8 text-sm text-gray-400"><a href="#work" class="hover:text-white transition">Work</a><a href="#services" class="hover:text-white transition">Services</a><a href="#about" class="hover:text-white transition">About</a></div><a href="#" class="bg-violet-600 hover:bg-violet-700 px-6 py-2.5 rounded-full text-sm font-bold transition">Get a Quote</a></div></nav>
<section class="min-h-screen flex items-center pt-20 relative"><div class="absolute top-0 right-0 w-96 h-96 bg-violet-600/10 rounded-full blur-3xl"></div><div class="max-w-7xl mx-auto px-6 relative z-10"><p class="text-violet-400 font-bold text-sm uppercase tracking-widest mb-4">Award-Winning Creative Agency</p><h1 class="text-7xl md:text-9xl font-black leading-none tracking-tighter mb-6">We Build<br/>Digital<br/><span class="text-violet-500">Empires</span></h1><p class="text-gray-400 text-lg max-w-lg mb-8">Strategy, design, and technology that transforms brands into cultural icons. From startups to Fortune 500.</p><a href="#" class="bg-violet-600 hover:bg-violet-700 px-8 py-4 rounded-full font-bold transition inline-block">Start a Project</a><div class="flex gap-12 mt-16"><div><p class="text-4xl font-black text-violet-500">300+</p><p class="text-gray-500 text-sm">Projects Delivered</p></div><div><p class="text-4xl font-black text-violet-500">12</p><p class="text-gray-500 text-sm">Awards Won</p></div><div><p class="text-4xl font-black text-violet-500">$2B+</p><p class="text-gray-500 text-sm">Revenue Generated</p></div></div></div></section>
<section id="services" class="py-32"><div class="max-w-7xl mx-auto px-6"><h2 class="text-5xl font-black tracking-tighter mb-16">Services</h2><div class="grid md:grid-cols-3 gap-8">
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-violet-500/30 transition"><div class="text-4xl mb-4">🎨</div><h3 class="text-xl font-bold mb-2">Brand Identity</h3><p class="text-gray-500 text-sm">Logo design, brand strategy, visual systems, and comprehensive brand guidelines.</p></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-violet-500/30 transition"><div class="text-4xl mb-4">💻</div><h3 class="text-xl font-bold mb-2">Web Development</h3><p class="text-gray-500 text-sm">High-performance websites and web apps built with modern frameworks and pixel-perfect design.</p></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-violet-500/30 transition"><div class="text-4xl mb-4">📱</div><h3 class="text-xl font-bold mb-2">Mobile Apps</h3><p class="text-gray-500 text-sm">Native iOS and Android apps with stunning UX, built to scale from day one.</p></div>
</div></div></section>
<footer class="border-t border-white/5 py-16"><div class="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8"><p class="text-2xl font-black tracking-tighter">NOVA<span class="text-violet-500">.</span></p><p class="text-gray-600 text-sm">© 2026 NOVA Creative. All rights reserved.</p></div></footer>
</body></html>`;

const ecommerceTemplate = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><script src="https://cdn.tailwindcss.com"></script><title>LUXE Store</title></head><body class="bg-black text-white font-sans">
<nav class="fixed w-full z-50 bg-black/80 backdrop-blur-xl border-b border-white/5"><div class="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center"><a href="#" class="text-2xl font-black tracking-tighter">LUXE<span class="text-emerald-500">.</span></a><div class="hidden md:flex gap-8 text-sm text-gray-400"><a href="#shop" class="hover:text-white transition">Shop</a><a href="#new" class="hover:text-white transition">New Arrivals</a><a href="#about" class="hover:text-white transition">About</a></div><a href="#" class="bg-emerald-600 hover:bg-emerald-700 px-6 py-2.5 rounded-full text-sm font-bold transition">Shop Now</a></div></nav>
<section class="min-h-screen flex items-center pt-20"><div class="max-w-7xl mx-auto px-6"><p class="text-emerald-400 font-bold text-sm uppercase tracking-widest mb-4">Premium Lifestyle Brand</p><h1 class="text-7xl md:text-9xl font-black leading-none tracking-tighter mb-6">Wear<br/>The<br/><span class="text-emerald-500">Future</span></h1><p class="text-gray-400 text-lg max-w-lg mb-8">Sustainable luxury fashion crafted with precision. Every piece is made from recycled materials with zero compromise on style.</p><a href="#" class="bg-emerald-600 hover:bg-emerald-700 px-8 py-4 rounded-full font-bold transition inline-block">Shop Collection</a></div></section>
<section id="shop" class="py-32"><div class="max-w-7xl mx-auto px-6"><h2 class="text-5xl font-black tracking-tighter mb-16">Bestsellers</h2><div class="grid md:grid-cols-3 gap-8">
<div class="bg-gray-900 border border-white/5 rounded-3xl overflow-hidden group hover:border-emerald-500/30 transition"><div class="h-64 bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center text-6xl">👕</div><div class="p-6"><h3 class="font-bold mb-1">Essential Tee — Midnight</h3><p class="text-emerald-500 font-bold">$89</p></div></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl overflow-hidden group hover:border-emerald-500/30 transition"><div class="h-64 bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center text-6xl">🧥</div><div class="p-6"><h3 class="font-bold mb-1">Tech Jacket — Onyx</h3><p class="text-emerald-500 font-bold">$249</p></div></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl overflow-hidden group hover:border-emerald-500/30 transition"><div class="h-64 bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center text-6xl">👟</div><div class="p-6"><h3 class="font-bold mb-1">Runner X — Carbon</h3><p class="text-emerald-500 font-bold">$179</p></div></div>
</div></div></section>
<footer class="border-t border-white/5 py-16"><div class="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8"><p class="text-2xl font-black tracking-tighter">LUXE<span class="text-emerald-500">.</span></p><p class="text-gray-600 text-sm">© 2026 LUXE. All rights reserved.</p></div></footer>
</body></html>`;

const saasTemplate = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><script src="https://cdn.tailwindcss.com"></script><title>NEXUS AI Platform</title></head><body class="bg-gray-950 text-white font-sans">
<nav class="fixed w-full z-50 bg-gray-950/80 backdrop-blur-xl border-b border-white/5"><div class="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center"><a href="#" class="text-2xl font-black tracking-tighter">NEXUS<span class="text-blue-500">.</span></a><div class="hidden md:flex gap-8 text-sm text-gray-400"><a href="#features" class="hover:text-white transition">Features</a><a href="#pricing" class="hover:text-white transition">Pricing</a><a href="#docs" class="hover:text-white transition">Docs</a></div><a href="#" class="bg-blue-600 hover:bg-blue-700 px-6 py-2.5 rounded-full text-sm font-bold transition">Get Started Free</a></div></nav>
<section class="min-h-screen flex items-center pt-20 relative"><div class="absolute top-20 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-blue-600/10 rounded-full blur-3xl"></div><div class="max-w-7xl mx-auto px-6 text-center relative z-10"><p class="text-blue-400 font-bold text-sm uppercase tracking-widest mb-4">AI-Powered Analytics Platform</p><h1 class="text-6xl md:text-8xl font-black leading-none tracking-tighter mb-6">Intelligence<br/>At <span class="text-blue-500">Scale</span></h1><p class="text-gray-400 text-lg max-w-2xl mx-auto mb-8">Transform raw data into actionable insights with our AI engine. Real-time analytics, predictive modeling, and automated reporting — all in one platform.</p><div class="flex gap-4 justify-center"><a href="#" class="bg-blue-600 hover:bg-blue-700 px-8 py-4 rounded-full font-bold transition">Start Free Trial</a><a href="#" class="border border-white/20 hover:border-white/40 px-8 py-4 rounded-full font-bold transition">Live Demo</a></div><div class="flex gap-12 justify-center mt-16"><div><p class="text-4xl font-black text-blue-500">10M+</p><p class="text-gray-500 text-sm">Data Points/sec</p></div><div><p class="text-4xl font-black text-blue-500">99.9%</p><p class="text-gray-500 text-sm">Uptime</p></div><div><p class="text-4xl font-black text-blue-500">5K+</p><p class="text-gray-500 text-sm">Companies</p></div></div></div></section>
<section id="features" class="py-32"><div class="max-w-7xl mx-auto px-6"><h2 class="text-5xl font-black tracking-tighter mb-16 text-center">Features</h2><div class="grid md:grid-cols-3 gap-8">
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-blue-500/30 transition"><div class="text-4xl mb-4">📊</div><h3 class="text-xl font-bold mb-2">Real-Time Dashboards</h3><p class="text-gray-500 text-sm">Live data visualization with custom widgets, alerts, and team sharing.</p></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-blue-500/30 transition"><div class="text-4xl mb-4">🤖</div><h3 class="text-xl font-bold mb-2">AI Predictions</h3><p class="text-gray-500 text-sm">Machine learning models that forecast trends and identify opportunities automatically.</p></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8 hover:border-blue-500/30 transition"><div class="text-4xl mb-4">🔗</div><h3 class="text-xl font-bold mb-2">500+ Integrations</h3><p class="text-gray-500 text-sm">Connect Salesforce, HubSpot, Stripe, Shopify, and hundreds more with one click.</p></div>
</div></div></section>
<section id="pricing" class="py-32 bg-gradient-to-b from-gray-950 to-gray-900"><div class="max-w-7xl mx-auto px-6 text-center"><h2 class="text-5xl font-black tracking-tighter mb-16">Pricing</h2><div class="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8"><h3 class="font-bold text-lg mb-2">Starter</h3><p class="text-4xl font-black mb-4">Free</p><p class="text-gray-500 text-sm mb-6">For individuals and small teams getting started.</p><ul class="text-left text-sm text-gray-400 space-y-2 mb-8"><li>✓ 1K events/day</li><li>✓ 3 dashboards</li><li>✓ 7-day retention</li></ul><a href="#" class="block w-full text-center border border-white/20 py-3 rounded-full font-bold hover:border-white/40 transition">Get Started</a></div>
<div class="bg-gray-900 border-2 border-blue-500 rounded-3xl p-8 relative"><div class="absolute -top-3 left-1/2 -translate-x-1/2 bg-blue-600 text-xs font-bold px-4 py-1 rounded-full">POPULAR</div><h3 class="font-bold text-lg mb-2">Pro</h3><p class="text-4xl font-black mb-4">$49<span class="text-lg text-gray-500">/mo</span></p><p class="text-gray-500 text-sm mb-6">For growing teams that need advanced analytics.</p><ul class="text-left text-sm text-gray-400 space-y-2 mb-8"><li>✓ Unlimited events</li><li>✓ Unlimited dashboards</li><li>✓ AI predictions</li><li>✓ 1-year retention</li></ul><a href="#" class="block w-full text-center bg-blue-600 hover:bg-blue-700 py-3 rounded-full font-bold transition">Start Trial</a></div>
<div class="bg-gray-900 border border-white/5 rounded-3xl p-8"><h3 class="font-bold text-lg mb-2">Enterprise</h3><p class="text-4xl font-black mb-4">Custom</p><p class="text-gray-500 text-sm mb-6">For large organizations with custom needs.</p><ul class="text-left text-sm text-gray-400 space-y-2 mb-8"><li>✓ Everything in Pro</li><li>✓ Dedicated support</li><li>✓ Custom integrations</li><li>✓ SLA guarantee</li></ul><a href="#" class="block w-full text-center border border-white/20 py-3 rounded-full font-bold hover:border-white/40 transition">Contact Sales</a></div>
</div></div></section>
<footer class="border-t border-white/5 py-16"><div class="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8"><p class="text-2xl font-black tracking-tighter">NEXUS<span class="text-blue-500">.</span></p><p class="text-gray-600 text-sm">© 2026 NEXUS Inc. All rights reserved.</p></div></footer>
</body></html>`;

export const fallbackTemplates = {
  coffee: coffeeTemplate,
  fitness: fitnessTemplate,
  agency: agencyTemplate,
  ecommerce: ecommerceTemplate,
  saas: saasTemplate,
};
